apiVersion: v1
kind: Service
metadata:
  name: newsum-service
  namespace: site
spec:
  type: LoadBalancer
  selector:
    app: newsum-app
  sessionAffinity: None
  externalTrafficPolicy: Cluster  
  ports:
    - port: 443
      targetPort: 443

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: newsum-hpa
  namespace: site
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: newsum-deployment
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50
