apiVersion: v1
kind: Secret
metadata:
  name: news-api-secrets
  namespace: site
type: Opaque
stringData: # stringData를 사용하여 일반 텍스트로 값을 입력하면 Kubernetes가 자동으로 Base64 인코딩합니다.
  NAVER_CLIENT_ID: "5h99wt7tQemGiYytM7xz"
  NAVER_KEY: "GMJ9ubjYQ7"
  GOOGLE_API_KEY: "AIzaSyDKlkvOMog_FeOWVeo9hS55PBX6_KU-vRo"
  DB_HOST: "mysql-service"
  DB_USER: "nsuser"
  DB_PASSWORD: "newsum"
  DB_NAME: "news_db"
  PORT: "3001"

