apiVersion: v1
kind: PersistentVolume
metadata:
  name: raid-pv
spec:
  capacity:
    storage: 10Gi  # RAID 디스크의 실제 용량에 맞게 조정하세요
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/raid10  # RAID 디스크가 마운트된 경로
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker2  # worker2 노드에만 스케줄링
