apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-env
  namespace: site
data:
  MYSQL_ROOT_PASSWORD: mysql
  DB_HOST: mysql-service
  DB_NAME: news_db
  DB_USER: nsuser
  DB_PASSWORD: newsum

